name: Terraform Workflow

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: windows-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.0"
      env:
        # Required for Windows runners to execute PowerShell scripts
        POWERSHELL_EXECUTION_POLICY: 'Bypass'
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve